### ISSUE TITLE
Write Python graph generation program. Figure out file output format for the C++ program

### ISSUE THREAD

**Issue by hamikm** [hamikm/cit_cs143_network_sim#6]

**Comment by hamikm** [comment]
Rather than having each netdevice contain a reference to the containing simulation i think it would make sense to absra

**Comment by hamikm** [comment]
Oops, accidentally closed this

**Comment by hamikm** [comment]
God dammit.

**Comment by azercephi** [comment]
Graph generation program written. Sample json format data file and graph generation program will be added later.

**Comment by hamikm** [comment]
Make a makefile target called "graph" that runs your program
